Amazon_Url = 'https://www.amazon.com'
Product_Name1 = 'Apple iPhone 11 pro max'
Browser = 'chrome'
Timeout = '10s'
Enter = '66'
Time = '4s'
Product_Name2 = 'Apple iPhone 11 Pro Max, 64GB, Midnight Green - For Sprint (Renewed)'
Sign_In_Text = 'Sign-In'
Product_Name3 = 'Apple iPhone 11 Pro Max, 64GB, Midnight Green'
PinCode = '90201'
### Mobile Environment Detials ###
Appium_Server = 'http://127.0.0.1:4723/wd/hub'
Platform_Name = 'Android'
Automation_Name = 'Appium'
Platform_Version = '8.0.0'
Device_Name = 'ce11160bab38a11e04'
appPackage = 'in.amazon.mShop.android.shopping'
AppActivity = 'com.amazon.mShop.home.HomeActivity'
